### ISSUE TITLE
Config and plugins [RFC]

### ISSUE THREAD

**Issue by nicoduclare** [bebverse/universe#10]
### Problem

BEB dimension aims to be a highly scalable node.js server with a plugin architecture for maximum developer flexibility.

### Solution
1. A config/plugins directory with standard parameters
2. Ability for the server to load plugins from the directory

### Example
```
// config/dimension.yaml

"port": 1493
"user": beb
```

```
// config/plugins.yaml

beb.spam_fee: 
  "enabled": true
  "payable_address": YOUR_ADDRESS
  "payable_amount": "0.01"
  "chain_id": 1 // ETH

my.custom_plugin
  "id": "custom-plugin"
  "entry_point": "./plugins/custom_plugin/index.js"
```

**Comment by nicoduclare** [comment]
@vrypan I think having SPAM fees be a standard plugin makes more sense than having it baked into the protocol. Enable more customization + extensibility

The plugin can provide an on-chain payable address or the address of a payable contract like yours https://github.com/bebverse/dimension/issues/5

**Comment by cryptojcdenton** [comment]
Alternatively, plugins are baked into bebverse/universe and enabled through flags. A plugin system might be hard to scale and support as the internal APIs could change over time.

e.g.

`./universe --spam-fee 0.01 --anti-spam`

**Comment by cryptojcdenton** [comment]
Lets go with the flag approach for additional functionality
