### ISSUE TITLE
EVM Multi-Chain Interoperability [RFC]

### ISSUE THREAD

**Issue by cryptojcdenton** [bebverse/universe#3]
## Problem

There has been an explosion of chains from [Ethereum](https://ethereum.org/) to [Polygon](https://polygon.technology), [Moonbeam](https://moonbeam.network/), and more. Given the web3 social ecosystems building around them, it will likely lead to chain maximalism, where users choose allegiance to their network and client developers add little interoperability - as an example, see the interoperability support between Bitcoin and Ethereum. As of today, there is no meta-protocol for communication uniting all these EVM chains.

## Solution
The [BEB protocol](https://github.com/bebverse/protocol) becomes multi-chain interoperable, taking another step towards our vision of a web3 SMTP.  Any self-hosted dimension can support a number of chains hosted through various BEB registrars: for example, a dimension hosted by @pugson at `music.beb` can also be accessed as `music.X` (Polygon) and `music.X` (Moonbeam). 

## Plan
We plan to integrate the most common EVM chains and their wallets into the BEB protocol and our client for dimension support. Clients such as our own at [BEBverse](https://beb.xyz) will support initialization of multi-chain dimensions and support multi-chain communication, but still reserve the ability to treat their preferred chain (such as .beb) as a first-class citizen in their UI.

**Comment by ethjcdenton** [comment]
Shoutout to @vrypan for giving us the nudge in this direction!

**Comment by ethjcdenton** [comment]
Shared to Twitter and Farcaster:
https://twitter.com/ethjcdenton/status/1618637877340172290
farcaster://casts/0x786f746a5d4d2ca7434e2e938909ef287a5854c82afb946bc001a682dcadd9e8/0x786f746a5d4d2ca7434e2e938909ef287a5854c82afb946bc001a682dcadd9e8

**Comment by ethjcdenton** [comment]
Let's proceed with Farcaster as a first TLD integration :)

**Comment by ethjcdenton** [comment]
Updating this to multi-chain, which in our opinion is a more pressing issue

**Comment by cryptojcdenton** [comment]
After consideration, we're deprioritizing multi-chain to focus our efforts on making a better self-hosted dimension protocol and products. 

If mint fees are unreasonable (e.g. greater then $100 USD), we can easily deploy our registrar to another EVM-compatible chain.
